### ISSUE TITLE
Admin Panel Size Input Method in Add Product Form

### ISSUE THREAD

**Issue by tharushkadinujaya05** [tharushkadinujaya05/CollegeWebProject-EcommerceSite#37]
Description:
In the “Add Product” form, the size attributes are currently inputted via a text input field. This method is prone to user error and does not provide a clear, standardized way to select size options. Instead, a dropdown menu should be used to allow users to select from predefined sizes such as S, M, L, XL, XXL.

Steps to Reproduce:

	1.	Navigate to the “Add Product” form.
	2.	Locate the input field for size attributes.
	3.	Attempt to enter size values manually.

Expected Behavior:
A dropdown menu should be present instead of a text input field, allowing users to select sizes from a predefined list (e.g., S, M, L, XL, XXL).

Suggested Fix:

	•	Replace the current text input field for sizes with a dropdown menu.
	•	Populate the dropdown with predefined size options (S, M, L, XL, XXL).

Additional Information:

	•	Using a dropdown menu for size selection will improve form usability and reduce errors related to inconsistent size entries.
	•	Ensure that the dropdown menu integrates well with the existing form layout and functionality.

**Comment by trevonakesh** [comment]
Fixed
